version: '3.4'
services:
  db:
    build:
      context: .
      dockerfile: "DockerfileDB"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example 
  web:
    build:
      context: ../
      dockerfile: "./docker/DockerfileWEB"
    volumes:
      - "../:/var/www/html/"
      - "./site.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    depends_on:
      - db
  php:
    build:
      context: ../
      dockerfile: ./docker/DockerfilePHP
    volumes:
      - "../:/var/www/html/"
    ports:
      - "9000:9000"
